openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1

paths:
  /sys/frp:
    get:
      summary: set frp config
      operationId: getFrpcConfig
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FrpcConfig'
    post:
      summary: Set system time
      operationId: setFrpcConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FrpcConfig'
      responses:
        '200':
          description: OK

  /sys/frp/enable:
    get:
      summary: enable/disable frpc
      operationId: getFrpEnable
      responses:
        '200':
          description: OK
          content:
            application/json:
              ref: '#/components/schemas/Enabled'
    post:
      summary: enable/disable frpc
      operationId: setFrpEnable
      requestBody:
        content:
        application/json:
          schema:
          $ref: '#/components/schemas/Enabled'
      responses:
        '200':
        description: OK

  /sys/slave:
    get:
      summary: get slave config
      operationId: getSlaveConfig
      responses:
        '200':
        description: OK
        content:
          application/json:
          ref: '#/components/schemas/Slaves'
    post:
      summary: set slave config
      operationId: setSlaveConfig
      requestBody:
        content:
        application/json:
          schema:
          $ref: '#/components/schemas/Slave'
      responses:
        '200':
          description: OK

  /sys/cmd:
    post:
      summary: execute command
      operationId: executeCommand
      requestBody:
        content:
        application/json:
          schema:
          $ref: '#/components/schemas/Command'
      responses:
        '200':
          description: OK

  /sys/time:
    get:
      summary: get system time
      operationId: getSystemTime
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  time:
                    type: string
                    description: system time
    post:
      summary: Set system time
      operationId: setSystemTime
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                time:
                  type: string
                  description: system time
      responses:
        '200':
          description: OK

  /sys/time/ntp:
    get:
      summary: get ntp config
      operationId: getNtpConfig
      responses:
        '200':
        description: OK
        content:
          application/json:
          schema:
            $ref: '#/components/schemas/NtpConfig'
    post:
      summary: set ntp config
      operationId: setNtpConfig
      requestBody:
        content:
        application/json:
          schema:
          $ref: '#/components/schemas/NtpConfig'
      responses:
        '200':
          description: OK

  /sys/disk/usage:
    get:
      summary: get disk usage
      operationId: getDiskUsage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                ref: '#/components/schemas/DiskUsage'

  /sys/disk/managed:
    get:
      summary: get managed disk usage
      operationId: getManagedDiskUsage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: set managed disk usage
      operationId: setManagedDiskUsage
      requestBody:
        content:
        application/json:
          schema:
          type: array
          items:
            type: string
      responses:
        '200':
        description: OK

  /sys/disk/config:
    get:
      summary: get disk config
      operationId: getDiskConfig
      responses:
        '200':
        description: OK
        content:
        application/json:
        schema:
          $ref: '#/components/schemas/DiskSpaceConfig'
    post:
      summary: set disk config
      operationId: setDiskConfig
      requestBody:
        content:
        application/json:
        schema:
        $ref: '#/components/schemas/DiskSpaceConfig'
      responses:
        '200':
        description: OK

  /sys/plan:
    get:
      summary: get plan
      operationId: getPlan
      responses:
        '200':
        description: OK
        content:
        application/json:
        schema:
          type: array
          items:
            $ref: '#/components/schemas/Plan'
    post:
      summary: set plan
      operationId: setPlan
      requestBody:
        content:
        application/json:
        schema:
          type: array
          items:
            $ref: '#/components/schemas/Plan'
      responses:
        '200':
        description: OK

  /sys/add_version:
    post:
      summary: add version
      operationId: addVersion
      requestBody:
        content:
        application/json:
        schema:
          $ref: '#/components/schemas/VersionPackage'
      responses:
        '200':
        description: OK

  /sys/module/config:
    get:
      summary: get module config
      operationId: getModuleConfig
      responses:
        '200':
        description: OK
        content:
        application/json:
        schema:
          $ref: '#/components/schemas/ModuleConfig'
    post:
      summary: set module config
      operationId: setModuleConfig
      requestBody:
        content:
        application/json:
        schema:
          $ref: '#/components/schemas/ModuleConfig'
      responses:
        '200':
        description: OK

  /sys/init:
    get:
        summary: get init config
        operationId: getInitConfig
        responses:
            '200':
            description: OK

  /sys/download:
    post:
        summary: download file
        operationId: downloadFile
        requestBody:
            content:
            application/json:
            schema:
            $ref: '#/components/schemas/File'
        responses:
            '200':
            description: OK

  /sys/upload:
    post:
        summary: upgrade
        operationId: upgrade
        requestBody:
            content:
            application/json:
            schema:
            $ref: '#/components/schemas/File'
        responses:
            '200':
            description: OK

components:
    schemas:
      FrpcConfig:
        type: object
        properties:
          frps_addr:
            type: string
            description: frps_addr
          frps_port:
            type: integer
            format: int64
            description: frps_port
          config_units:
            type: array
            items:
              $ref: '#/components/schemas/FrpcConfigUnit'
      FrpcConfigUnit:
        type: object
        properties:
          name:
            type: string
            description: name
          local_ip:
            type: string
            description: local_ip
          local_port:
            type: string
            description: local_port
          remote_port:
            type: string
            description: remote_port
      Enabled:
        type: object
        properties:
          enabled:
            type: boolean
            description: enabled
      Slave:
        type: object
        properties:
          id:
            type: string
            description: ID
          type:
            type: string
            description: Type
            enum: [ linux, android ]
          ip:
            type: string
            description: IP
          username:
            type: string
            description: Username
            required: false
          password:
            type: string
            description: Password
            required: false
          key:
            type: string
            description: Key
            required: false
      Slaves:
        type: array
        items:
          $ref: '#/components/schemas/Slave'
      Command:
        type: object
        properties:
          cmd:
            type: string
            description: Command
          target:
            type: string
            description: Target machine
            required: false
      NtpConfig:
        type: object
        properties:
          ntp_server:
            type: string
            description: ntp server
          enalbe:
            type: boolean
            description: enable
      DiskUsage:
        type: object
        properties:
          usage:
          type: string
          description: disk usage
      DiskSpaceConfig:
        type: object
        properties:
          enabled:
            type: boolean
            description: Disk space management enabled
          threshold:
            type: integer
            format: int64
            description: Disk space threshold in percentag
          retention:
            type: integer
            format: int64
            description: Disk space retention in days
      Plan:
        type: object
        properties:
          cmd:
            type: string
            description: Command
          target:
            type: string
            description: Target machine
            required: false
          rule:
            type: string
            description: Rule like crontab
      VersionPackage:
        type: object
        properties:
          version:
            type: string
            description: version
          modules:
            type: array
            items:
              ref: '#/components/schemas/Module'
          pakcage:
            type: string
            description: pakcage in Base64
      Module:
        type: object
        properties:
          name:
            type: string
            description: name
          version:
            type: string
            description: version
          config_file:
            type: string
            description: config_file
      ModuleConfig:
        type: object
        properties:
          name:
            type: string
            description: name
          config:
            type: string
            description: config
      File:
        type: object
        properties:
            path:
                type: string
                description: path
            content:
                type: string
                description: content
            is_dir:
                type: boolean
                description: is_dir
